##===- projects/mypass/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../../

#
# List all of the subdirectories that we will compile.
#
LIBRARYNAME=lib583HW1
LOADABLE_MODULE=1

include $(LEVEL)/Makefile.common
